settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: workers-cloudflare-com # unique identifier
    name: workers.cloudflare.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://workers.cloudflare.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

 
   - id: Reddit
    name: reddit.com
    description: 'Reddit is a network of communities where people can dive into their interests, hobbies and passions'
    url: 'https://www.reddit.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
    
   - id: Youtube
    name: youtube.com
    description: 'YouTube is an online video sharing and social media platform headquartered in San Bruno, California'
    url: 'https://www.youtube.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
   
   
   - id: 1337X
    name: 1377x.to
    description: '1337x is a website that provides a directory of torrent files and magnet links used for peer-to-peer file sharing through the BitTorrent protocol'
    url: 'https://www.1377x.to/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
    
    
  - id: Piratebay
    name: thepiratebay.org
    description: 'The Pirate Bay (sometimes abbreviated as TPB) is an online index of digital content of entertainment media and software'
    url: 'https://thepiratebay.org/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  
